@startuml
left to right direction

object ユーザー {
    ユーザーID
    ユーザー名
}

object タスク {
    タスク名
    期日
    ステータス
    延期回数
    作成日
    担当ユーザーID
}

タスク "0..n" --> "1" ユーザー : ユーザーID参照

note bottom of ユーザー: - ユーザーIDはユニーク\n- ユーザー名は非ユニーク\n- ユーザー名は半角英数字で1〜10文字
note bottom of タスク: - 作成時のステータスはtodo\n- ステータスの種類はtodo,doing,done\m\n- ステータスは1段階ずつ変わる\n- ステータスは不可逆\n- 期日で設定できるのは未来の期日のみ\n- 期日は１度だけ延期できる\n- 期日は設定時の30日以内で設定

@enduml