[[constraint]]
  name = "github.com/gin-gonic/gin"
  version = "1.3.0"

[[project]]
  name = "github.com/go-sql-driver/mysql"
  version = "v1.4.0"

[[constraint]]
  name = "github.com/jinzhu/gorm"
  version = "1.0.0"

[prune]
  go-tests = true
  unused-packages = true
